name: Buildaeploy # Workflow
on: [push,workflow_dispatch] # Trigger the workflow on push events
jobs:
   test:  #here test is the name of the job
      runs-on: ubuntu-latest 
      steps:
         - name: Get Code
           uses: actions/checkout@v4

         - name: Install node 20
           uses: actions/setup-node@v4
           with:
                node-version: '20'
         - name: print node version
           run: node --version
         - name: Install Dependencies
           run: npm ci
         
         - name: run test cases
           run: npm test
   build: # This job will build the application
      needs: test  # Ensure this job runs after the test job
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v4

        - name: Install node 20
          uses: actions/setup-node@v4
          with:
                node-version: '20'
        - name: Install Dependencies
          run: npm install

        - name: Build Application
          run: npm run build
        - name: upload dist artifact
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist

   deploy:  # This job will deploy the application
      needs: build  # Ensure this job runs after the test job
      runs-on: ubuntu-latest
      steps: 
          - name: Get Code
            uses: actions/checkout@v4
  
          - name: Download dist artifact
            uses: actions/download-artifact@v4
            with:
              name: dist-files

          - name: Deploy Application
            run: echo "Deploying application to the server..."
           
         
        
         

         