name: deployAction # Workflow
on: [push,workflow_dispatch] # Trigger the workflow on push events
jobs:
   test:  #here greet is the name of the job
      runs-on: ubuntu-latest 
      steps:
         - name: Get Code
           uses: actions/checkout@v4

         - name: Install node 20
           uses: actions/setup-node@v4
           with:
                node-version: '20'
         - name: print node version
           run: node --version
         - name: Install Dependencies
           run: npm ci
         - name: run test cases
           run: npm test
         
        
         

         